### ISSUE TITLE
Review survey launch checklist

### ISSUE THREAD

**Issue by lauggh** [worldiaday/StateofIAReport#7]
- [x] Welcome and instructions
- [x] Thank you and confirmation
- [x] Closed survey message
- [x] Questionnaire/questions
- [x] Dry Run / Preview
- [x] Finalize
- [x] Survey rules and settings
- [ ] Screener -- redirect to other languages??

**Comment by lauggh** [comment]
Launched with no screener. When translations are available, then add screener to redirect.
